{
	"name": "Assertion Tests",
	"summary": {
		"tests": 6,
		"failures": 2,
		"errors": 1,
		"time": 0,
		"running": false,
		"messages": []
	},
	"tests": [
		{
			"name": "testPass",
			"summary": {
				"tests": 2,
				"failures": 0,
				"errors": 0,
				"time": 0,
				"running": false,
				"messages": [
					{
						"type": "pass",
						"message": ""
					},
					{
						"type": "pass",
						"message": ""
					}
				]
			}
		},
		{
			"name": "testFail",
			"summary": {
				"tests": 2,
				"failures": 2,
				"errors": 0,
				"time": 0,
				"running": false,
				"messages": [
					{
						"type": "fail",
						"message": "Test fail() call"
					},
					{
						"type": "fail",
						"message": "assert(false) guaranteed to fail"
					}
				]
			}
		},
		{
			"name": "testError",
			"summary": {
				"tests": 1,
				"failures": 0,
				"errors": 1,
				"time": 0,
				"running": false,
				"messages": [
					{
						"type": "error",
						"message": "http://clutch.syger.it/tests/clutch/unit-test-tests.js(234) Error: Test error() call\nError(\"Test error() call\")@:0\n()@http://clutch.syger.it/tests/clutch/unit-test-tests.js:234\n(\"testError\")@http://clutch.syger.it/projects/clutch/src/unit-test.js:85\n()@http://clutch.syger.it/projects/clutch/src/unit-test.js:167\nstoreClutchTests(runClutchTests,\"/run-fixture/tests/clutch/unit-test-tests.json\",\"/tests/clutch/view-unit-test-tests.html\")@http://clutch.syger.it/clutch/js/saver.js:74\nonload([object Event])@http://clutch.syger.it/tests/clutch/run-unit-test-tests.html:1\n@:0\n"
					}
				]
			}
		},
		{
			"name": "testAssert",
			"summary": {
				"tests": 1,
				"failures": 0,
				"errors": 0,
				"time": 0,
				"running": false,
				"messages": [
					{
						"type": "pass",
						"message": ""
					}
				]
			}
		}
	]
}